# Generated by Django 5.1.4 on 2025-08-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbttest',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
