# Generated by Django 5.1.4 on 2025-08-09 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_session_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.session'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partial')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.term'),
        ),
        migrations.AlterField(
            model_name='result',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.session'),
        ),
        migrations.AlterField(
            model_name='result',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.term'),
        ),
    ]
