# Generated by Django 5.1.4 on 2025-09-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_studentprofile_graduated_studentprofile_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
